


mqtt_server_: '10.18.19.1'  #mqtt服务器地址
mqtt_port_: '1883'  #mqtt服务器端口
mqtt_user_: 'pi'  #mqtt服务器用户名
mqtt_password_: 'rarry'  #mqtt服务器密码
mqtt_prefix_: 'homeassistant'     #mqtt服务自动发现前缀
latitude_: '22.568017'  #经度
longitude_: '115.038915'  #维度
ota_password: 'xxxxxxxx'  #ota密码
web_user: 'esphome'  #网页用户名
web_password: 'xxxxxxxx'  #网页密码
wifi_ssid: 'iot_wl'  # wifi   ssid
wifi_password: 'xxxxxxxx'  #wifi密码
ap_ssid: 'esphome'   #wifi的ap模式下ssid
ap_password: 'xxxxxxxx'  #wifi的ap模式下密码
wifi_reboot_timeout: 1200s  #wifi断开情况下多久重启
mqtt_reboot_timeout: 1200s  #mqtt断开情况下多久重启