
      
text_sensor:
  - platform: template #配置文件版本
    name: "Config_Version"
    update_interval: 1h
    lambda: |-
      return {"${config_version}"};

  
  - platform: wifi_info
    ip_address:
      name: 'IP'
    mac_address:
      name: 'MAC'





sensor:
  - platform: internal_temperature
    id: cpu_temprature
    name: cpu_temprature
    unit_of_measurement: °C
    device_class: temperature
    filters:
      - median:
          window_size: 3
          send_every: 3
  - platform: wifi_signal
    name: "RSSI"
    update_interval: 60s

  - platform: sun
    name: Sun Elevation
    type: elevation
    internal: false
    filters:   
      - lambda: |-   

            auto index = id(sun_mode).active_index();
            //ESP_LOGE("ble_adv", " xxxx   %d", index.value());
            if (id(mqttconnect).state and index.has_value() and index.value()==0  ){
              if (  x >0 ){
                auto call = id(_light_back).turn_off();
                call.perform();
              }else {
                auto call = id(_light_back).turn_on();
                call.perform();
              }
            }
            return x  ;
  - platform: wifi_signal
    name: "RSSI"
    update_interval: 60s

